routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CreateController;
use App\Http\Controllers\InicioController;
use App\Http\Controllers\EmpresaController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/productos', function () {
    return view('productos.index');
});

Route::get('/productos/create',[CreateController::class,'create']);
*/
Route::resource('productos',CreateController::class)->middleware('auth');



Route::resource('productos.empresa',EmpresaCommentController::class);

Auth::routes();

Route::get('/', [InicioController::class, 'index'])->name('welcome');




Route::group(['middleware' => 'auth'], function(){
Route::get('/home', [CreateController::class, 'index'])->name('home');

});

resources/views/productos/create.blade.php
    
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

        <div class="container">
    <h1>Nuevo Producto</h1>
    <br>
    <div class="row">
    <div class="col-xl-l2">
    
<form action="{{url('/productos')}}" method="post" enctype="multipart/form-data">
@csrf
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

<h4><label for="nombre">Nombre</label></h4>
<input class="form-control" value="" type="text" placeholder="Nombre del producto" name="nombre" required>
<br>
 
<div class="form-group shadow-textarea">
<h4> <label for="exampleFormControlTextarea6">Descripcion</label></h4>
  <textarea class="form-control z-depth-1"  id="exampleFormControlTextarea6" name="descripcion" rows="3" placeholder="Escribe una descripcion del producto..." required></textarea>
</div>
<br>
 
<div class="form-group shadow-textarea">
   <h4> <label for="">Foto</label></h4>
   <label for=""></label>
   
    <input  value="" class="form-control form-control-lg" accept="image/*" name="foto" id="formFileLg" type="file" / required>
</div>
<br>
 
<div class="form-group shadow-textarea">
<h5><label for="">Categoria:</label></h5>
<select name="" id="">
    <option value=""></option>
</select>
</div>
<br>
 
<div class="form-group shadow-textarea">
<h6><label for="">Tipo de producto:</label></h6>
<select name="" id="">
    <option value=""></option>
</select>
</div>
<br>
 
<input type="submit" class="btn btn-success"value="Guardar">
</form>
<a href="{{url('productos/')}}">Volver</a>

 
    </div>
    </div>
         </div>
  
 
</body>
</html>


                </div>
            </div>
        </div>
    </div>




   

resources/views/productos/edit.blade.php
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

        <div class="container">
    <h1>Editar Producto</h1>
    <br>
    <div class="row">
    <div class="col-xl-l2">
    
<form action="{{route('productos.update',$productos->id)}}" method="post" enctype="multipart/form-data">
@csrf
@method('PUT')
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

<h4><label for="nombre">Nombre</label></h4>
<input class="form-control" value="{{$productos->nombre}}" type="text" placeholder="Nombre del producto" name="nombre">
<br>
 
<div class="form-group shadow-textarea">
<h4> <label for="exampleFormControlTextarea6">Descripcion</label></h4>
  <textarea class="form-control z-depth-1"  id="exampleFormControlTextarea6" name="descripcion" rows="3" placeholder="Escribe una descripcion del producto...">{{$productos->descripcion}}</textarea>
</div>
<br>
 
<div class="form-group shadow-textarea">
<img src="{{asset('storage').'/'.$productos->foto}}" width="120px">
   <h4> <label for="">Foto</label></h4>
   <label for=""></label>
   
    <input value="" class="form-control form-control-lg" accept="image/*" name="foto" id="formFileLg" type="file" />
</div>
<br>
 
<div class="form-group shadow-textarea">
<h5><label for="">Categoria:</label></h5>
<select name="" id="">
    <option value=""></option>
</select>
</div>
<br>
 
<div class="form-group shadow-textarea">
<h6><label for="">Tipo de producto:</label></h6>
<select name="" id="">
    <option value=""></option>
</select>
</div>
<br>
 
<input type="submit" class="btn btn-success"value="Guardar">
</form>

<a href="{{url('productos/')}}">Volver</a>
 
    </div>
    </div>
         </div>
  
 
</body>
</html>


                </div>
            </div>
        </div>
    </div>




   

resources/views/productos/empresa.blade.php
<h1>Empresa</h1>

resources/views/productos/index.blade.php
@extends('layouts.app-admin')     
  @section('content')
      <head>
      
 
      </head>       
      <a href="{{url('productos/create')}}" style="margin:15px;">Nuevo Producto</a>
      <a href="{{url('productos/empresa')}}">Empresa</a>
      <form  action="{{route('productos.index')}}" method="get">   
<div class="input-group mb-3" >
  <input type="text" class="form-control"placeholder="Busca aqui" name="texto" style="margin-top: 15px;">
  <div class="input-group-append">
    <button class="btn btn-success" type="submit" style="margin-top: 15px; ">Buscar</button>
  </div>
</div>
        </form>
    <table class="table">
  <thead>
  
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Foto</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  @foreach($creates as $create)
    <tr>
     
      <td>{{$create->id}}</td>
      <th>{{$create->nombre}}</th>
      <td>{{$create->descripcion}}</td>
      <td><img src="{{asset('storage').'/'.$create->foto}}" class="img-fluid img-thumbnail" width="120px"></td>
      <td><a href="{{route('productos.edit',$create->id)}}" class="btn btn-light" style="color:blue;">Editar</a></td>


    <td>
      <form action="{{ url('productos/'.$create->id ) }}"  method="post">
      @csrf
      {{ method_field('DELETE') }}
      <button onclick="return confirm('¿Seguro Que quieres borrar este registro?')" class="btn btn-light" style="color:red;">Borrar</button>
     </form>
    </td>
    </tr>
   
      @endforeach
  </tbody>
</table>

{!! $creates->links() !!}
                </div>
            </div>
        </div>
    </div>
    
    @endsection